### ISSUE TITLE
"list index out of range" with kera

### ISSUE THREAD

**Issue by FantineFu** [odysseaspap/msc_thesis#1]
Hi,

There is something wrong when building models, but I just change the dataset path.

![image](https://user-images.githubusercontent.com/30807653/100580351-bc890b00-3320-11eb-9f2e-1f6c0ee74dba.png)

Besides, could you please kindly provide some pre-trained model?

**Comment by Kannan-Balakrishnan** [comment]
@FantineFu were you able to solve the issue....I am also experiencing the same problem......

**Comment by Kannan-Balakrishnan** [comment]
If you are using windows and anaconda, then most likely you will get this error because of the version mismatch. I would suggest you to follow these steps:
1.Create a new virtual environment in anaconda
2. conda install -c conda-forge keras=2.1
3. conda install -c conda-forge tensorflow-gpu=1.13.1
4. pip install tensorflow-gpu==1.13.1
5. pip install tensorflow-graphics-gpu
Then try to run your program...Hope this solves the issue.
